- .gitignore
- .travis.yml
- example/conf.py
- example/index.rst
- mlx/traceability.py
- setup.py
- tox.ini
contributing to #2 
using sphinx.util.logging for warning messages
adapted example to spawn a few warnings (for manual test)
issue #2 is not resolved (yet) as i couldn't find a way to get the source linenumber from a docutils object... Needs more investigation for possible fix...
> Warnings using sphinx.util.logging

- mlx/traceability.py
- setup.py
> contributing to Issue #8: fix typo in are_related()

- .travis.yml
- tox.ini
Not supported by pytest anymore
> Drop py33 support

- README.rst
- example/index.rst
- mlx/traceability.py
- setup.cfg
Add some statistics about coverage at the top of an item-matrix
> statistics for item-matrix, admonition title for all directives

- README.rst
- example/SRS.rst
- example/index.rst
- mlx/traceability.py
- mlx/traceable_item.py
- tests/test_traceable_collection.py
- tests/test_traceable_item.py
See readme: generate a table with source items in rows, and target items in columns. An 'x' on a co-ordinate in the table, marks a matching relation between source and target.
> Directive for 2D-matrix

- README.rst
- example/index.rst
- mlx/traceability.py
- tox.ini
add hit/miss words to fill the cells as arguments
improved example with more test cases
> 2d matrix improvements

- README.rst
- example/index.rst
- mlx/traceability.py
> Add option to not show captions on item-matrix and other directives

- README.rst
- example/conf.py
- example/index.rst
- mlx/traceability.py
- mlx/traceable_collection.py
- mlx/traceable_item.py
- tests/test_traceable_collection.py
- tests/test_traceable_item.py
- tox.ini
> Assert attribute values against configured regular expression

- README.rst
- example/conf.py
- example/index.rst
- mlx/traceability.py
contributing to #33 
includes work for #59
> Attribute to string

- README.rst
- example/index.rst
- mlx/traceability.py
- setup.py
- tox.ini
Add way to list attributes on items in a table
contributing to #33
> Item attributes matrix

- mlx/traceability.py
- setup.py
> When no translation to string is given, use attribute/relation raw string

- README.rst
- example/index.rst
- mlx/traceability.py
> Add nocaptions option for item-attributes-matrix directive

- README.rst
- example/index.rst
- mlx/traceability.py
- mlx/traceable_collection.py
- mlx/traceable_item.py
- setup.py
- tests/test_traceable_item.py
- tox.ini
> Sort attribute list

- README.rst
- example/index.rst
- mlx/traceability.py
- setup.py
> Allow filtering on attribute values for various directives

- README.rst
- example/index.rst
- mlx/traceability.py
> Issue #32 - no item-tree output for latex/pdf builder

- README.rst
- doc/integration_test_report.rst
- mlx/traceable_base_class.py
- mlx/traceable_item.py
- tests/test_traceable_base_class.py
- tests/test_traceable_collection.py
- tox.ini
no functional change, just moving stuff to a base class.
> Introduce base class

- .codeclimate.yml
- .pylintrc
- MANIFEST.in
- setup.cfg
- Replace deprecated `engines` by `plugins`
- Remove deprecated `ratings` section
- Add plugins: bandit, git-legal, pylint, sonar-python, pep8
- Increase some thresholds if it makes sense for this project
> Change codeclimate configuration

- tests/test_traceable_collection.py
- tests/test_traceable_item.py
Fixes `DeprecationWarning: invalid escape sequence \w`
> Fix invalid escape sequences

- .gitignore
- README.rst
- doc/conf.py
- mlx/traceability.py
> Add ability to configure color of linked items based on regex

- .codeclimate.yml
- .pylintrc
- doc/integration_test_report.rst
- mlx/directives/item_2d_matrix_directive.py
- mlx/directives/item_attribute_directive.py
- mlx/directives/item_attributes_matrix_directive.py
- mlx/directives/item_directive.py
- mlx/directives/item_link_directive.py
- mlx/directives/item_list_directive.py
- mlx/directives/item_matrix_directive.py
- mlx/directives/item_pie_chart_directive.py
- mlx/directives/item_tree_directive.py
- mlx/traceability.py
- mlx/traceability_exception.py
- mlx/traceability_item_element.py
- mlx/traceable_collection.py
- mlx/traceable_item.py
Refactored `TraceableItem` class and fixed some typos/docstrings in the plugin.
Increased `method-count` in code climate from 20 to 25.
Enabled Pylint's `max-public-methods=20` check
> Refactor TraceableItem

- mlx/directives/item_pie_chart_directive.py
Refactor the part in `ItemPieChart` class that prepares pie chart data and builds the image.
> Refactor pie chart node

- mlx/directives/item_attribute_directive.py
- mlx/directives/item_directive.py
- mlx/traceable_base_directive.py
> Refactor Item class

- .travis.yml
- setup.py
- tox.ini
> Obsolete python 2.7

- doc/design.rst
- mlx/assets/traceability.js
- mlx/traceable_base_node.py
> Show caption when hovering over item

- README.rst
- mlx/directives/item_attribute_directive.py
To fix pdf build when using Sphinx>=2.0.0.
> Don't generate empty dl in item-attribute

- README.rst
- mlx/directives/checkbox_result_directive.py
- mlx/directives/checklist_item_directive.py
- mlx/traceability.py
> Fix KeyError when traceability_checklist is empty

- README.rst
- doc/.env.example
- doc/conf.py
- tox.ini
> Improve documentation about checklist-item directive

- mlx/assets/traceability.js
- mlx/directives/item_directive.py
- mlx/traceable_base_node.py
The style of the added link gets undone by JavaScript.
> Add permalink to traceability items

- doc/requirements.rst
- mlx/traceable_base_node.py
- tests/test_item_directive.py
Fix for bug introduced in #128
> Fix captions being appended to item ID in pdf with nocaptions option set

- mlx/directives/item_directive.py
- mlx/directives/item_matrix_directive.py
- mlx/traceable_base_node.py
- mlx/traceable_collection.py
- tests/test_item_directive.py
- tox.ini
Followup of discussion in #178
> Moved regex matching to its own function + filter external links out item-matrix

- MANIFEST.in
- SECURITY.md
Adding a security policy for the plugin.
> Add Security policy

- CONTRIBUTING.md
- README.md
- doc/contributing.rst
- doc/readme.rst
Taken from warnings-plugin since it seems generic enough. Maybe even too generic?
> Add contributing description

- doc/_static/css/extra.css
- doc/design.rst
- doc/example_usage.rst
- doc/integration_test_report.rst
- doc/unit_test.rst
- doc/usage.rst
- mlx/directives/item_matrix_directive.py
- mlx/directives/item_pie_chart_directive.py
- mlx/traceable_collection.py
- tests/directives/test_item_pie_chart.py
> Link source to targets via intermediate items in item-matrix

- mlx/traceability.py
> Fix Support markup for checklist item ID in MR description

- doc/usage.rst
Improve documentation for item-matrix by tweaking the wording and punctuation.
> Improve documentation for item-matrix

- doc/integration_test_report.rst
- mlx/directives/item_matrix_directive.py
- mlx/traceable_item.py
This support should have been added to https://github.com/melexis/sphinx-traceability-extension/pull/212.
> Support filtering on attributes with empty value

- doc/integration_test_report.rst
- doc/usage.rst
- mlx/assets/traceability.js
- mlx/directives/checklist_item_directive.py
- mlx/directives/item_directive.py
- mlx/directives/item_list_directive.py
- Support titles in item body
- Render item body in item-list with markup
Closes #226
> Support titles in item body

- doc/integration_test_report.rst
- doc/usage.rst
- mlx/directives/item_matrix_directive.py
- tox.ini
Add option `:coverage:` to evaluate coverage of item-matrix.
> Add option to evaluate coverage of item-matrix

- doc/unit_test.rst
- doc/usage.rst
- mlx/directives/item_relink_directive.py
- mlx/traceability.py
- mlx/traceable_item.py
Add `item-relink` directive
Closes #251
> Add directive to relink items

- doc/conf.py
- doc/requirements.rst
- doc/usage.rst
- mlx/directives/item_pie_chart_directive.py
> Support filtering of source items on attributes in item-piechart

- doc/integration_test_report.rst
- doc/requirements.rst
- doc/usage.rst
- mlx/directives/item_pie_chart_directive.py
- tox.ini
> Support configuration of the colors of the item-piechart

- doc/.env.example
- doc/conf.py
- doc/usage.rst
- mlx/traceability.py
- Added: support configuration of GIT platform in traceability_checklist
- Fixed: unexpected responses to GET requests to the GitLab/GitHub API now result in warnings instead of a crash of the documentation build
Closes #272
> Support configuration of GIT platform in traceability_checklist

- doc/Makefile
- mlx/directives/item_tree_directive.py
- setup.py
- tox.ini
Address docutils deprecation warnings and allow doc build parameters to be customized via the command line
> Address docutils deprecation warnings

- .github/workflows/python-package.yml
Fix for #291 
I used the information in https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
> Run workflow on tag after #291

- mlx/directives/item_attributes_matrix_directive.py
Making the `ItemAttributesMatrix` more in line with `ItemMatrix` and easier to understand in my opinion.
> Minor refactoring of ItemAttributesMatrix

- doc/requirements.rst
- doc/unit_test.rst
- mlx/traceability/directives/item_pie_chart_directive.py
> item-piechart <<attribute>> filtering should give priority to a missing attribute

- mlx/traceability/directives/item_pie_chart_directive.py
- mlx/traceability/traceable_collection.py
> Order item-piechart slices more logically

- doc/integration_test_report.rst
- doc/requirements.rst
- doc/usage.rst
- mlx/traceability/directives/item_matrix_directive.py
- mlx/traceability/directives/item_pie_chart_directive.py
- mlx/traceability/traceable_base_node.py
> Improvements for pie chart matrix

- .gitignore
- MANIFEST.in
- mlx/traceability/assets/traceability.js
- mlx/traceability/traceability.py
- pyproject.toml
- setup.py
- require Ctrl to be pressed in combination with RMB to collapse a row of an item-matrix (#382)
- show tooltip when hovering over a row of an item-matrix to inform users about the new functionality and 
- add package's version number to the filename of the JavaScript file so that your browser always uses the correct content
- minify JavaScript file
> Improve usability of #382

- mlx/traceability/traceability.py
- mlx/traceability/traceable_base_node.py
- mlx/traceability/traceable_collection.py
Fixing some bugs in #396 by purging the traceability data of changed source files. A partial rebuild resulted in a crash.
> Fix partial rebuild issues
