melexis/sphinx-traceability-extension

- .travis.yml
- tox.ini
Removed sphinx<1.3 from tox due to template not available at that time
(2014).
Proving issue #5
> Proof issue #5 - adapt tox to build example for several sphinx versions

- README.rst
This updates the `README.rst` file to include instructions for adding the static javascript file in `conf.py`.
Closes #13
> Add message in README.rst about including static javascript assets

- .gitignore
- mlx/traceability.py
Cover for documentation mistakes where RST items contain links to the same items twice (maybe through the automatic reverse link).
open question: do we raise a warning when a duplicate relation is detected?
> No duplicate relations

- mlx/traceability.py
using docutils.parsers.rst.Directive
http://www.sphinx-doc.org/en/stable/changes.html
> Prepare for sphinx 1.7: sphinx.util.compat.Directive is removed

- mlx/traceability.py
- mlx/traceable_item.py
- setup.py
- tests/test_traceable_collection.py
- tests/test_traceable_item.py
- tox.ini
sphinx >= 1.6 allows for a callback for consistency check after parsing all input files. Use this callback to perform a self-test on the collection of items.
> Consistency check

- README.rst
- example/SSS.rst
- example/index.rst
- mlx/traceability.py
Using the title of an item-matrix (was not used before).
Adding title for columns of an item-matrix.
And small updates in the example.
> item-matrix: use title, add title for columns

- mlx/traceability.py
When no relations were specified in an item-matrix (=wildcard all
available relationships), the external relationships were not included.
> item-matrix: external relationships were not included when no relation specified

- README.rst
- example/index.rst
- mlx/traceability.py
- mlx/traceable_collection.py
- mlx/traceable_item.py
- tests/test_traceable_collection.py
- tests/test_traceable_item.py
This PR contributing to #33 adds attributes to
- items: items can be attributed with a configurable set of attributes
- item-list: lists of items can be filtered for a specific attribute value (regex)
Attributes are probably useful for other directives (matrix, 2d-matrix, tree) but that is still todo for now. Ideas are welcome however in #33.
> Initial implementation for item attributes (item and item-list)

- README.rst
- example/conf.py
- mlx/traceability.py
The traceability_render_relationship_per_item configuration parameter now only affects relationship rendering and leaves the display of attributes unchanged.
> Change behavior of traceability_render_relationship_per_item to not affect display of attributes

- README.rst
- mlx/traceability.py
When rendering many of the tables into PDF there is a tendency for the tables to run out past the margins. The LaTeX writer normally forces the longtable environment when the number of rows is greater than 30. However, when using normal table directives in sphinx you can normally pass in the `:class: longtable` attribute to those directives to force longtable environment in LaTeX. This change just passes the `:class:` attribute down to the `Table` node where it is processed normally by the downstream transforms and writers.
> Add support for manually specifying longtable

- mlx/traceability.py
Convert the caught `Exception` object to `str` before passing it to a `logger` function. This conversion is needed explicitly when Sphinx' -W option is used and location information is available. In this case, Sphinx builds the error message by means of concatenation of the `location` and `exception` objects.
Closes issue #85
> Fix TypeError in case of TraceabilityException with Sphinx' -W option

- README.rst
- mlx/traceable_collection.py
- tests/test_traceable_collection.py
Change the sorting behaviour of the `:sort:` option in `.. item-attributes-matrix::` from naturally to alphabetically.
Fixes issue #84
> Sort items alphabetically when sortattributes argument is used

- .pylintrc
- mlx/directives/item_2d_matrix_directive.py
- mlx/directives/item_attribute_directive.py
- mlx/directives/item_attributes_matrix_directive.py
- mlx/directives/item_directive.py
- mlx/directives/item_link_directive.py
- mlx/directives/item_list_directive.py
- mlx/directives/item_matrix_directive.py
- mlx/directives/item_pie_chart_directive.py
- mlx/directives/item_tree_directive.py
- mlx/traceability.py
- mlx/traceability_exception.py
- mlx/traceability_item_element.py
- mlx/traceable_collection.py
- Split off each directive with its node class into a separate file
- Created `ItemElement` parent class for custom node classes and moved utility functions inside this parent class
- Moved `report_warning()` to `traceability_exception.py`
Closes #51
> Refactoring traceability.py

- mlx/directives/item_2d_matrix_directive.py
- mlx/directives/item_attribute_directive.py
- mlx/directives/item_attributes_matrix_directive.py
- mlx/directives/item_directive.py
- mlx/directives/item_link_directive.py
- mlx/directives/item_list_directive.py
- mlx/directives/item_matrix_directive.py
- mlx/directives/item_pie_chart_directive.py
- mlx/directives/item_tree_directive.py
- mlx/traceability.py
- mlx/traceability_item_element.py
- Add line number to warning about target item being undefined (closes #2)
- Make `PendingItemXref` inherit from `ItemElement` (like all other node classes do)
- Pylint fix: shorten `perform_traceability_replacement` to `perform_replacement`
> More refactoring

- .codeclimate.yml
Only use the sonar-python complexity check by removing the code climate complexity check.
> Only use the sonar-python complexity check

- mlx/directives/item_pie_chart_directive.py
Refactored `perform_replacement` in `ItemPieChart`, which used a deeply nested structure, by using `loop_relationships` recursively.
I also fixed several occurences where the order of dictionary keys was used, while a dictionary's order isn't always deterministic.
> Refactor perform_replacement in ItemPieChart

- doc/design.rst
- mlx/directives/item_2d_matrix_directive.py
- mlx/directives/item_attribute_directive.py
- mlx/directives/item_attributes_matrix_directive.py
- mlx/directives/item_directive.py
- mlx/directives/item_link_directive.py
- mlx/directives/item_list_directive.py
- mlx/directives/item_matrix_directive.py
- mlx/directives/item_pie_chart_directive.py
- mlx/directives/item_tree_directive.py
- mlx/traceability.py
- mlx/traceable_base_directive.py
- mlx/traceable_base_node.py
Used as source by #109.
Renamed `ItemElement` to `TraceableBaseNode`.
Renamed `BaseDirective` to `TraceableBaseDirective`.
Converted public attributes and functions to protected where viable.
Updated design chart as requested in #104.
> Update class diagram

- mlx/directives/item_2d_matrix_directive.py
- mlx/directives/item_attribute_directive.py
- mlx/directives/item_attributes_matrix_directive.py
- mlx/directives/item_directive.py
- mlx/directives/item_link_directive.py
- mlx/directives/item_list_directive.py
- mlx/directives/item_matrix_directive.py
- mlx/directives/item_pie_chart_directive.py
- mlx/directives/item_tree_directive.py
- mlx/traceable_base_directive.py
- mlx/traceable_base_node.py
- mlx/traceable_collection.py
Refactored `process_options` to allow specifying the default value for a wider application of the function.
Refactored code that processes option flags by defining `check_option_presence()`.
Improved style of `option_spec` dictionary.
Fixed args documentation in `traceable_collection.py`.
Refactor the processing of the directive title by defining `process_title()`.
Add some missing docstrings.
> Refactor processing of options

- MANIFEST.in
- requirements.txt
- tox.ini
Requirements.txt is needed for automatic dependency detection in GitHub, so that we spread the word around.
> Add requirements txt for GitHub dependency detection

- mlx/directives/item_attributes_matrix_directive.py
- mlx/directives/item_directive.py
- mlx/directives/item_pie_chart_directive.py
- mlx/traceable_base_class.py
- mlx/traceable_base_directive.py
- mlx/traceable_base_node.py
The quotes should highlight the trailing comma more. Not sure how this can be clarified more without adding more code.
> Clarify warning about missing reference to source document.

- README.rst
- doc/conf.py
- mlx/assets/traceability.js
- mlx/directives/item_directive.py
- mlx/traceability.py
If an _item_ has any rendered _relationships_ or _attributes_, a button will be added on the right hand side that allows you to hide this info. 
Hiding (collapsing) all links on page load can be enabled by setting `traceability_collapse_links` to `True` in `conf.py`. The links are shown (uncollapsed) by default.
Closes #92
> Allow collapsing the traceability information for item

- .travis.yml
8 days ago Travis CI switched from using its default trusty dist to the newer xenial dist. Since then, plantuml could not be found so it didn't build. Apparently plantuml was contained in the trusty dist, but removed from the xenial dist. Explicitly installing plantuml fixes the issue. Travis CI should build the documentation now.
Closes #119
> Install plantuml in Travis CI using Xenial dist

- doc/checklist.rst
- doc/index.rst
- mlx/directives/checklist_item_directive.py
- tox.ini
This is an example to showcase the new _checklist-item_ directive. The checkboxes below are followed by item IDs that are defined using `.. checklist-item:: ` in _doc/checklist.rst_. The plugin adds an additional attribute to these items. For this example the name and values of this attribute are taken from the default values for the configuration variable `traceability_checklist` in _doc/conf.py_.
> Add checklist example

- mlx/traceability.py
Without this change the plugin ignores a checklist line in a pull/merge request that starts with a space before `- [ ]` . Spaces should be allowed.
> Allow spaces at the start of a line in a checklist in Markdown

- .codeclimate.yml
- mlx/assets/traceability.js
No longer rely on the presence of the _simple_ class of a dl element to add the button, but use the first dl element encountered. This fixes the issue where the button wasn't generated when using an older style theme/docutils version.
> Fix collapse button not being generated depending on docutils version

- README.rst
- doc/conf.py
- doc/integration_test_report.rst
- mlx/directives/item_attributes_matrix_directive.py
Closes #83
Added consistency to the module name used to add the plugin to the list of Sphinx extensions. It is now 'mlx.traceability' in conf.py and README. This is the way the plugin is added in mlx.coverity. I don't see a reason to have it differently here.
> Add transpose option

- mlx/traceability.py
- setup.py
- Using `requests.Session` object as a context manager to query for the checklist instead of directly calling `requests.get()`.
- Added `requests` module to the list of requirements (even though `Sphinx` already requires it).
> Using requests.Session object for the checklist query

- mlx/assets/traceability.js
This fixes the issue where the collapse button can end up above the item's title bar depending on the theme's style sheet and Sphinx version in use. This is how it should've been implemented in the first place.
> Tweak positioning of collapse button

- mlx/directives/item_directive.py
- mlx/traceable_base_node.py
In HTML: the dl element is not placed inside the paragraph, but after it as a sibling. This change removes the empty paragraph. No side effect in LaTeX.
Adding a css class called _item_ to the admonition node to give users the ability to change the CSS for only these admonitions.
> Tweak generated admonitions

- mlx/directives/item_directive.py
- mlx/traceable_base_directive.py
When using a custom stylesheet the addition of an empty definition list element can cause unwanted whitespace between the item's title bar and the item's content. This fixes that issue.
> Don't add dl element when it's empty

- mlx/directives/item_list_directive.py
This change prevents the generation of an empty bullet_list node when for each empty _item-list_ to fix the LaTeX error below, reported by @dryodon :
`LaTeX Error: Something's wrong--perhaps a missing \item.`
The plugin wants to generate an emtpy bullet list for an empty _item-list_, which results in the code below in traceability.tex:
```
\begin{itemize}
\end{itemize}
```
LaTeX expects at least one `\item`.
> No longer generate empty bullet list in case of an empty item-list

- doc/.env.example
- doc/checklist.rst
- doc/conf.py
- mlx/traceability.py
Multiple merge request IDs can be defined as a string with comma-separation, e.g. `'121,138'`. This string can be added to the `traceability_checklist` dict as a value for `'merge_request_id'` or as an environment variable called `MERGE_REQUEST_ID`.
Closes #137 
The checklist below gets queried when building the example documentation:
> Facilitate configuration of multiple merge request IDs in traceability_checklist dict

- mlx/traceability.py
- mlx/traceable_collection.py
Removed unused `env` argument in `add_checklist_attribute` and `query_checklist` functions.
Minor style fixes regarding indentation.
> Remove unused env argument

- mlx/traceability.py
- `match` does the same thing as `search` with a leading `^`, but is faster.
- `fullmatch` is now used instead of `match` when trying to match leftover item IDs in the `query_results` dictionary. This won't change the behavior, however. It just clarifies the code.
> Use match instead of search with leading caret, and fullmatch where sensible

- README.rst
- doc/integration_test_report.rst
- mlx/directives/item_matrix_directive.py
- tox.ini
Add `group` attribute to item-matrix directive to group source items that do not have a target item.
Closes #145 
TODO:
> Add group attribute to item-matrix directive

- doc/integration_test_report.rst
- mlx/traceability.py
- mlx/traceable_base_directive.py
- tox.ini
The plugin will now report a warning when a custom attribute overlaps with a directive option, in which case the custom attribute definition will be ignored. 
Example of a warning when a custom traceability attribute `source` is defined by the user:
`WARNING: Your custom attribute 'source' overlaps with an option of directive(s) ['ItemMatrixDirective', 'Item2DMatrixDirective'] in which your attribute definition will be ignored.`
Closes #148
> Fix behavior in case of overlap between custom attributes and directive options

- .travis.yml
Currently the CI build fails the pdf build:
```
latexmk -pdf -dvi- -ps- -silent 'traceability.tex'
make[1]: latexmk: Command not found
Makefile:33: recipe for target 'traceability.pdf' failed
```
> Install Tex Live and latexmk packages for pdf build

- mlx/traceable_base_node.py
Fix `nocaptions` flag of `item` directive and `traceability_item_no_captions` config value not working
Bug introduced in #151
> Fix nocaptions flag of item directive not working

- README.md
- tox.ini
Let tox use `sphinx_selective_exclude>=1.0.3`. Version `1.0.2` is broken.
Removed Process section from toctree since it felt out of place and its link is broken on PyPI anyway. https://github.com/pypa/warehouse/issues/4064
> Use latest sphinx_selective_exclude in test environment

- mlx/traceable_collection.py
When trying to export the JSON file to a subfolder `_static` of the output folder, e.g. `./doc/_build/_static/database.json`, I got a `FileNotFoundError` because `./doc/_build/_static/` does not exist. This PR will make the tool create the subfolder(s) for you.
> Create target location for JSON export when it does not exist yet

- doc/design.rst
- doc/integration_test_report.rst
- doc/requirements.rst
- doc/usage.rst
- mlx/directives/attribute_sort_directive.py
- mlx/directives/item_directive.py
- mlx/traceability.py
- mlx/traceable_collection.py
- mlx/traceable_item.py
- tests/test_traceable_collection.py
- tox.ini
Resolves #160 
Example usage:
```
.. attribute-sort::
:filter: RQT-
:sort: status value aspice
```
> Add configurability for attribute sorting

- mlx/traceability.py
- mlx/traceable_base_node.py
- mlx/traceable_collection.py
- tests/test_traceable_collection.py
Items with no reference to their source document and with a relationship to a defined item can now get redirected to the configured notification item.
Completes functionality in https://github.com/melexis/sphinx-traceability-extension/pull/162
> Redirect missing references of linked items to notification item

- doc/usage.rst
- mlx/jira_interaction.py
- mlx/traceability.py
- tests/test_jira_interaction.py
Exceptions raised by the [Jira ticket creation feature](https://melexis.github.io/sphinx-traceability-extension/usage.html#jira-ticket-creation) are converted to warnings by default. If you want these errors to keep
crashing your build, you can set ``errors_to_warnings`` to a falsy value.
Most warnings will now start with `'Jira interaction failed:'` to make them easier to get [excluded by mlx-warnings](https://melexis.github.io/warnings-plugin/readme.html?highlight=exclude#exclude-matches-with-regexes) if desired.
> Convert Jira errors into warnings by default

- mlx/jira_interaction.py
- tests/test_jira_interaction.py
Fixed the name of the field used to set the Original Estimate field of a Jira ticket.
> Fix setting of Original Estimate field

- mlx/jira_interaction.py
- mlx/traceability.py
- tests/test_jira_interaction.py
Fix layout for `item-tree` directive. Bug introduced since since [v4.7.0](https://github.com/melexis/sphinx-traceability-extension/releases/tag/v4.7.0) by https://github.com/melexis/sphinx-traceability-extension/pull/167.
Also, changed *Effort estimation* into *Effort estimate* when appending the value of the `:effort:` attribute to the description of a Jira ticket.
> Fix layout for item-tree directive

- mlx/jira_interaction.py
- tests/test_jira_interaction.py
- A colon will be added to the summary of the Jira ticket after the id of the parent item.
- If the item to create a Jira ticket for has no body, its caption will be used as the description of the ticket.
- Optional setting `description_head` has been added, allowing users to add something to the description of the ticket via conf.py.
> Tweak Jira ticket description

- MANIFEST.in
- doc/_static/css/extra.css
- doc/conf.py
- tox.ini
Pinning the version of [sphinx_rtd_theme](https://github.com/readthedocs/sphinx_rtd_theme) to 0.5.0 to generate the example documentation. This upgrade introduces an unwanted effect to the rendered `item-tree` directive that we now override by an extra stylesheet on top.
> Tweak layout of example documentation

- doc/usage.rst
Adds documentation for the new configuration option for the description of a Jira ticket that was added in https://github.com/melexis/sphinx-traceability-extension/pull/173
> Document configuration option for the description of a Jira ticket

- mlx/directives/item_directive.py
- mlx/directives/item_pie_chart_directive.py
- mlx/directives/item_tree_directive.py
- mlx/traceable_base_directive.py
- mlx/traceable_base_node.py
- mlx/traceable_collection.py
- mlx/traceable_item.py
Removed unnecessary calls to `natsort.natsorted`. 96.3% of the calls to this function while building the example documentation was unnecessary.
> Improve performance of plugin

- doc/usage.rst
- mlx/jira_interaction.py
- tests/test_jira_interaction.py
Add an optional setting `traceability_jira_automation['notify_watchers']`, which is set to `False` by default, to let Jira notify a ticket's watchers of its creation by setting the assignee field of the ticket after the watchers have been added instead of during the ticket's creation.
Note that a notification is only triggered when a change in the ticket occurs. Explicitly setting the default assignee - after the Jira ticket has been already been created while resorting to the default assignee - will not trigger a notification.
This is essentially a workaround because Jira can't be configured to notify a watcher when they are added as a watcher.
> Add option to notify a Jira ticket's watchers of its existence

- doc/usage.rst
- mlx/jira_interaction.py
- mlx/traceable_item.py
- tests/test_jira_interaction.py
Add flexibility to `traceability_jira_automation['relationship_to_parent']`. Currently only a string is allowed to define the relation to look for parent items. The first parent item from that list is used. This behavior is not deterministic enough when the item to generate a Jira ticket for has multiple items linked to it with the same relationship.
This PR adds support for a sequence (e.g. a tuple, a list) as configured value. This sequence should have the relationship as the first element and a regex to match the ID of the desired parent item as the second element. Backward compatibility is ensured by keeping for support for the string as value.
> Add flexibility to traceability_jira_automation['relationship_to_parent']

- doc/integration_test_report.rst
- mlx/directives/item_matrix_directive.py
The source column of the item-matrix should always be sorted naturally, also when external items are used. The sorting was missing in the [v7.0.0](https://github.com/melexis/sphinx-traceability-extension/releases/tag/v7.0.0) release.
> Sort source column of item-matrix when external items are used

- mlx/assets/traceability.js
Closes https://github.com/melexis/sphinx-traceability-extension/issues/191
This is a patch for the following issues:
- external themes may set the CSS style `clear: both` on the admonition div, causing the arrow button to be pushed out of the admonition bar and become invisible (white arrow on white background)
- if an item-directive is preceded by an internal reference definition, e.g. `.. _sw_requirements:`, the arrow button didn't appear
FYI @bwi-mlx @bavovanachte
> Ensure visibility of arrow button to collapse traceability

- doc/integration_test_report.rst
- doc/usage.rst
- mlx/directives/item_matrix_directive.py
- mlx/traceable_item.py
- tests/test_attribute_link.py
- tests/test_traceable_item.py
This PR adds the `:sourcetype:` option to the *item-matrix* directive. It is an additional filter for source items next to the `:source:` option. It filters on the relationships of the source item instead of the item's ID.
On top of #195.
Resolves #194.
> Add an option to item-matrix to filter source items on relationships

- mlx/traceability.py
Currently the version shown for mlx.traceability in Sphinx' error log is `unknown version` like so:
`mlx.traceability (unknown version) from /usr/local/lib/python3.7/dist-packages/mlx/traceability.py`
This PR will display the version number of the installed plugin instead:
`mlx.traceability (7.3.0) from /usr/local/lib/python3.7/dist-packages/mlx/traceability.py`
> Include the plugin's version in Sphinx' error log

- doc/usage.rst
- mlx/traceability.py
Support markup of `checklist-item` ID in description of merge/pull request.
Example of a checklist item that the plugin ignored because of the markup:
I've updated the description of https://github.com/melexis/sphinx-traceability-extension/pull/121 to show that this is supported.
> Support markup for checklist item ID in MR description

- doc/integration_test_report.rst
- doc/usage.rst
- mlx/directives/item_matrix_directive.py
Closes #204 
Add option `intermediatetitle` to `item-matrix` directive. This option is required to show intermediate items when the option `intermediate` is used.
> Add option to show intermediate items in item-matrix

- .github/workflows/python-package.yml
I found the solution [here](https://github.community/t/trigger-job-on-tag-push-only/18076/2). It seems that `${{ github.event.release.created }}` doesn't exist or do what we want as seen [here](https://github.com/melexis/sphinx-traceability-extension/actions/runs/894066055).
> CI/CD: Fix conditional to trigger deploy job

- .github/workflows/python-package.yml
The documentation on GitHub Pages has been removed after the switch to GitHub actions because the artifacts from the test job didn't get passed to the deploy job. Let's fix this and create a release to publish the documentation to https://melexis.github.io/sphinx-traceability-extension/.
Followed the following guide: https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow
> Fix empty GitHub Pages

- tox.ini
The changes to `docutils/writers/html5_polyglot/__init__.py` in [docutils>=0.17](https://docutils.sourceforge.io/HISTORY.html#release-0-17-2021-04-03) are incompatible with [sphinx-rtd-theme](https://pypi.org/project/sphinx-rtd-theme/). Support for docutils==0.17 has been added in Sphinx==4.x in [this PR](https://github.com/sphinx-doc/sphinx/pull/9125).
> Fix HTML layout of contents directive

- doc/integration_test_report.rst
- doc/usage.rst
- mlx/assets/traceability.js
- mlx/directives/item_list_directive.py
Add new flag `:showcontents:` to `item-list` directive.
Example output:
> Add flag to item-list to show contents of items

- doc/configuration.rst
- mlx/traceability.py
After these changes only `traceability_callback_per_item` is defined instead of custom names. I think this is easier and clearer. I also showcased how to add an attribute in the example. 
I added the `functional` attribute definition to the plugin because only having the `non_functional` attribute defined limits what you can do with it. Think about filtering source items of a matrix on attributes.
> Improve documentation of callback functionality

- doc/integration_test_report.rst
- doc/usage.rst
- mlx/directives/item_matrix_directive.py
Prioritize `:onlycovered:` option of `item-matrix` directive over `:group:` option.
I was surprised that this wasn't the case already, so I'm classifying this as a bug.
Closes #234
> Prioritize :onlycovered: option of item-matrix over :group:

- doc/conf.py
- doc/integration_test_report.rst
- mlx/directives/item_directive.py
- mlx/traceable_base_class.py
- mlx/traceable_item.py
Support changes to item body in [callback function](https://melexis.github.io/sphinx-traceability-extension/configuration.html#callback-per-item-advanced). 
Simply use `TraceableItem.get_content()` and `TraceableItem.set_content()` to get and set the content as `str`.
> Support changes to item body in callback function

- doc/integration_test_report.rst
- doc/usage.rst
- mlx/directives/item_matrix_directive.py
- mlx/traceable_base_node.py
Add flag `:hidetitle:` to the `item-matrix` directive to hide the title.
> Add flag to item-matrix to hide the title

- tox.ini
`sphinx <= 2.1.9999` should not be marked as 'outdated' by requires.io as we want to explicitly test compatibility with the old Sphinx version.
> Let requires.io mark test version of Sphinx as green

- doc/usage.rst
- mlx/directives/item_matrix_directive.py
When the value of the `:type:` option contains a `|` character and the `:intermediate:` option is missing, the Sphinx build crashes with the following error message: 
```
sphinx.errors.ExtensionError: Handler <function process_item_nodes at 0x7f73b7487158> for event 'doctree-resolved' threw an exception (exception: list index out of range)
Extension error:
Handler <function process_item_nodes at 0x7f73b7487158> for event 'doctree-resolved' threw an exception (exception: list index out of range)
```
Let's raise a descriptive error instead.
> Avoid crash when linking via intermediate is done incorrectly

- mlx/directives/item_tree_directive.py
- mlx/traceability.py
- mlx/traceable_collection.py
- Report warning when circular relationship is found via child of child
- Catch the `RecursionError` that got raised when processing an item-tree with a circular relationship. Let's raise a clear error message instead of `exception: maximum recursion depth exceeded while calling a Python object`.
> Warn about circular relationships via child of child

- doc/requirements.rst
- mlx/directives/item_pie_chart_directive.py
Squash bug that caused the `item-piechart` directive to start off with the statistics of previously defined `item-piechart`s.
> Bugfix for multiple item-piecharts

- doc/integration_test_report.rst
- mlx/directives/item_matrix_directive.py
Targets that are linked via intermediates in an `item-matrix` will now be sorted naturally (excluding external targets) so that the same sorting behavior is used whether the `:intermediate:` option is used or not.
Closes #246
> Fix sorting behavior of targets via intermediates in item-matrix

- mlx/directives/item_matrix_directive.py
This bugfix is needed when `:targetcolumns:` or `:splittargets:` of the `item-matrix` directive is used and natural sorting of the targets is desired.
Part 2 of the solution for https://github.com/melexis/sphinx-traceability-extension/issues/246. These changes were missing from https://github.com/melexis/sphinx-traceability-extension/pull/253.
> Fix sorting behavior of split targets via intermediates in item-matrix

- mlx/directives/item_directive.py
- tox.ini
The `:class:` option may be useful to modify the lay-out of a traceable item in HTML format.
> Make :class: option work for item-directive

- doc/conf.py
- doc/configuration.rst
- mlx/directives/item_directive.py
- mlx/traceability.py
- tox.ini
To detect gaps in documentation, e.g. an attribute value that is required but missing, we need a second type of callback function: one that is called when all directives that can modify attributes of `TraceableItem`, e.g. the `attribute-link` directive, have been processed.
> Add secondary callback function to inspect items

- MANIFEST.in
- doc/Makefile
- mlx/traceability.py
- tools/doc-warnings.json
- tox.ini
Added support for sphinx parallel build to avoid the following warnings:
```
WARNING: the mlx.traceability extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
WARNING: doing serial read
```
I'm not sure if there would be any problem with allowing parallel builds in the traceability plugin.
> Indicate support for Sphinx parallel-write

- doc/usage.rst
Partially answers https://github.com/melexis/sphinx-traceability-extension/issues/272
`traceability_checklist['merge_request_id']` shall contain one or more comma-separated IDs of a merge/pull request. The order of these IDs matters. They are used to send sequential queries to GitLab/GitHub with each new response possibly overwriting the response of a previous query.
Imagine a configuration `traceability_checklist['merge_request_id'] = '3,1,9'`. If only the descriptions of MR 3 and 1 contain a specific `checklist-item`'s ID, the checkbox value in the desription of MR 1 will be used to determine and set the attribute value of that `checklist-item`.
However, I have never encountered a use case that lead me to configure multiple merge requests that contain the same checklist-item(s). I've …
> Clarify how multiple MR/PR IDs should be ordered in config variable traceability_checklist

- doc/conf.py
- doc/configuration.rst
- doc/usage.rst
- mlx/traceability.py
- mlx/traceability_exception.py
- mlx/traceable_base_node.py
Deprecation warnings can be hidden or shown like so:
hidden: `PYTHONWARNINGS=`
shown: `PYTHONWARNINGS=default::DeprecationWarning`
More info in https://www.sphinx-doc.org/en/master/man/sphinx-build.html#deprecation-warnings and https://docs.python.org/3/library/warnings.html#describing-warning-filters
> Document how regular expressions are handled

- doc/requirements.rst
- mlx/directives/item_pie_chart_directive.py
- setup.py
- tools/doc-warnings.json
- Fix: avoid that matplotlib generates a blank image when the item-piechart doesn't contain any documentation items
- Fix: add support for matplotlib==3.5.0
Resolves #271, resolves #249
Closes #275
> No longer generate a blank image for an empty item-piechart

- doc/conf.py
- doc/integration_test_report.rst
- doc/requirements.rst
- doc/usage.rst
- mlx/directives/item_pie_chart_directive.py
- mlx/traceability.py
- tools/doc-warnings.json
- Added `:sourcetype:` option to the `item-piechart` directive
- Added `:targettype:` option to the `item-piechart` directive
- Fixed a bug that resulted in using the `<<attribute>>` value of the nested target item that was parsed last as label instead of respecting the order of the arguments of the `:<<attribute>>:` option, or, in case of multiple target items, discarding the effect of those defined first.
Resolves #270
> Support filtering and labeling by relationship type for item-piechart

- doc/usage.rst
- mlx/directives/item_matrix_directive.py
A `filtertarget` flag is available for the `item-2d-matrix` directive, allowing the `<<attribute>>` filter to operate on target instead of source items.
This PR aims to provide the same functionality to the `item-matrix` directive, using the same approach as d3f25dcd21c9fb965cefcbf1d32c3ce22dbfc180.
A trivial use case would be being able to verify the coverage of requirements that are validated by a passing testcase:
```
.. item-matrix:: Testcase traceability matrix
:source: RQT
:target: TC
:sourcetitle: Requirement
:targettitle: Testcase
:type: validated_by
:filtertarget:
:status: PASS
```
> Add filtertarget flag to item-matrix directive

- doc/usage.rst
- mlx/directives/item_matrix_directive.py
This PR builds on #284, but I figured the additional changes might elicit enough discussion to warrant a separate PR.
At its core, this PR changes the internal plumbing of the `item-matrix` directive to allow rendering uncovered intermediates. At the same time (and this is probably where the discussion comes in), it changes the default behavior to display uncovered intermediates, as I figure it's the more useful alternative (more on that later). An `onlycoveredintermediates` flag, analogous to the existing `onlycovered` and `onlyuncovered` flags, is added to bring back the old behavior (to a point).
The goal of this PR is to support a workflow that I believe should be relatively common: verifying the coverage of requirements that are validated by a testcase who have themselves a test …
> Display uncovered intermediates by default in item matrix

- mlx/directives/item_attribute_directive.py
- mlx/traceable_base_node.py
When you specify the attribute identifier (the key in `traceability_attribute_to_string`) instead of the attribute name (the value in `traceability_attribute_to_string`) as the first argument for the `item-attribute` directive, links to this attribute definition don't work. This PR addresses this issue. Links to the attribute are produced by the `item` and `item-attributes-matrix` directives, for example.
> Use lower case to link to a TraceableAttribute

- mlx/traceable_item.py
Fix bug that causes some relationships to be hidden in the rendered `item`-directive.
> Fix bug that causes some relationships to be hidden

- mlx/traceable_base_node.py
- tests/directives/test_item_directive.py
When multiple HTML pages try to link to the same traceable item, it's possible some links are broken since [v9.0.0](https://github.com/melexis/sphinx-traceability-extension/releases/tag/v9.0.0). This PR fixes this bug.
Instead of caching the reference node with `href="#RQT-CAPTION"` in `env.traceability_ref_nodes` when the item `RQT-CAPTION` is located on the same HTML page, this PR changes it into `href="requirements.html#RQT-CAPTION"`. When the relative URI is different, a different reference node needs to be cached additionally.
> Fix broken links in HTML output

- doc/conf.py
- doc/usage.rst
- mlx/directives/item_pie_chart_directive.py
Added:
- The title can be hidden with the flag `:hidetitle:`.
- The generated images have the class `pie-chart` for easier manipulation with CSS.
- Use svg for HTML and pdf for PDF output instead of png.
Fixed:
- Long labels were not fully rendered. The width of the images will now adapt to the length of the labels instead of being fixed.
> item-piechart: support hidden titles and render long labels

- doc/integration_test_report.rst
- doc/usage.rst
- mlx/directives/item_link_directive.py
- mlx/directives/item_relink_directive.py
- mlx/traceable_collection.py
- tools/doc-warnings.json
Added:
- Add `source` and `target` options to `item-link` directive. They expect a regular expression.
--------------
Fixed:
- always process `item-relink` after `item-link` directive instead of using the order in which they are defined in the RST file(s)
> Support linking with item-link directive using regular expressions

- doc/unit_test.rst
- mlx/traceable_item.py
- tools/doc-warnings.json
PR #308 (v9.3.0) introduced a bug that caused the `item-link` and `item-relink` directives to only take effect from the moment they were processed during Sphinx' write stage. The linking must be done before any other directives are rendered, however, for the (re)linking to affect the entire output instead of from the point the document  they are defined in is rendered.
I've committed the fix to master branch already:
- https://github.com/melexis/sphinx-traceability-extension/commit/ab784f9a43e73bce35a827b2986a8a8dc77d8036
- 3b67a97bbac54fb0179505614eb27febe6a6a43c
- 18df53c723eb2a79452156e49d367ddb23efddb5
Fixed in this PR:
- Adjusting warning limit to account for the valid warning of `TraceableBaseNode.self_test` again, which was gone during v9.3.0: `WARNING: Item …
> Fix broken (re)linking from version 9.3.0

- doc/unit_test.rst
- mlx/directives/item_link_directive.py
- mlx/directives/item_relink_directive.py
- mlx/traceability.py
- tools/doc-warnings.json
Fixed:
- prevent bug introduced in 9.3.1 that causes a crash when duplicating a link/relationship with `item-link`
- `item-relink` can now be used more than once with the same `:remap:` value
- fix crash that occurred when a placeholder item in `item-relink`'s `:remap:` option did not have all of its targets transferred/relinked (to a valid item)
> Fix bugs in item-link and item-relink directives

- mlx/directives/item_pie_chart_directive.py
Avoid RuntimeWarning when more than 20 figures are open simultaneously.
Closes #315.
> Systematically close pyplot figures after use

- doc/usage.rst
- mlx/directives/attribute_link_directive.py
This PR adds a `nooverwrite` flag to the `attribute-link` directive, so that existing values are not clobbered.
A non-overwriting `attribute-link` directive can be used to give attributes default values:
```
.. attribute-link::
:filter: RQT-
:status: UNKNOWN
:nooverwrite:
```
Evil twin of #317.
> Add nooverwrite flag to attribute-link directive

- doc/configuration.rst
- mlx/traceability.py
- mlx/traceable_base_node.py
Finally address the `DeprecationWarning` and use `re.match` instead of `re.search` for regexes in `traceability_hyperlink_colors`
> Use `re.match` for regexes in `traceability_hyperlink_colors`

- doc/usage.rst
- mlx/directives/item_pie_chart_directive.py
This PR adds a `stats` flag to the `item-piechart` directive, bringing it in line with other directives such as `item-matrix`.
For now, as requested in the discussion of #318, only a warning is produced in order to let users know of an impending change in the default behavior.
`warnings.warn` was preferred over `report_warning` to avoid outputting one warning per pie chart.
> Add stats flag to item-piechart directive

- doc/usage.rst
- mlx/directives/item_link_directive.py
- mlx/directives/item_relink_directive.py
Same as for the attribute, we want to avoid a warning when existing relationship would be overwritten. This enables a bit more general usage of item-relink where items already containing correct links do not report warnings when they would be duplicated in project specific setting.
> Add nooverwrite flag for item-relink and item-link to reduce amount of warnings

- mlx/directives/item_relink_directive.py
During debugging of some item-relink directives I discovered that it is hard to find which relink item is to blame for the error, so adding a type to the error message makes that more user friendly.
> Add link type to the warning when target is missing

- mlx/directives/item_relink_directive.py
- mlx/traceability.py
For example, when `traceability_checklist['attribute_values'] = 'Yes,No'`, the only allowed values for that attribute were `Yes` and `No` even when `traceability_attributes` contains a regular expression. Let's not ignore that regular expression as there is a use case for this.
> Don't ignore regexp in traceability_attributes for traceability_checklist feature

- mlx/directives/item_pie_chart_directive.py
Lato is not always installed by default, so let's define `DejaVu Sans`, which ships with matplotlib, as the fallback font. Some versions of matplotlib generate the following warning many times when Lato is not found, which is annoying: `findfont: Generic family 'sans-serif' not found because none of the following families were found: Lato`
Closes #326
> Define a fallback font for pie charts

- doc/checklist.rst
- doc/integration_test_report.rst
- mlx/directives/attribute_link_directive.py
This PR fixes #322 by shamelessly copying ab784f9a43e73bce35a827b2986a8a8dc77d8036 and applying it to the `attribute-link` directive.
> Process attribute-link during consistency check event

- .github/workflows/python-package.yml
Master is failing because some actions use obsoleted nodejs version, so we need to upgrade them. While I was doing, I also upgraded other actions to their latest versions.
> Update actions due to deprecation warning

- mlx/traceability.py
- setup.py
Fixes local doc builds after unreleased #333 
Explanation in https://github.com/readthedocs/sphinx_rtd_theme/pull/1421
We cannot rely on `sphinx-rtd-theme` to add the jQuery for us as other HTML themes may also be used, even though they aren't recommended.
> Avoid sphinxcontrib.jquery==3.0.0 and enable plugin

- .github/workflows/python-package.yml
The deployment of v9.6.0 failed due to this.
> Fix CI job deploy

- doc/integration_test_report.rst
- mlx/directives/item_directive.py
When an `item`-directive contains the same item identifier, a warning was generated and the directive was processed. 
I think such a directive should not be processed and rendered but this is backwards incompatible.
> Completely disregard a duplicate item definition after warning about it

- doc/requirements.rst
- doc/usage.rst
- mlx/directives/item_pie_chart_directive.py
The `:stats:` flag was added in https://github.com/melexis/sphinx-traceability-extension/pull/323 (released in [v9.5.0](https://github.com/melexis/sphinx-traceability-extension/releases/tag/v9.5.0)) but did not yet have an effect because it was backwards incompatible. A warning was added to give users time to add this flag to any `item-piechart` directives they want to still display the statistics of.
> Hide pie chart statistics unless stats flag is provided

- doc/usage.rst
- mlx/directives/item_pie_chart_directive.py
This PR fixes the following perceived shortcomings of the `item-piechart` directive:
* Fix the reported values in the error message for the wrong number of color arguments when some of the labels are empty. Fixes #321.
* Make the default behavior to hide coverage statistics unless the `stats` flag is provided (c.f. #323), as is done with other directives such as `item-matrix`.
As per the discussion below, this PR introduces breaking changes and should be scheduled for the next major release.
> Fix some quality-of-life issues with item-piechart

- mlx/traceability.py
Check config variable `traceability_relationship_to_string` for completeness, aborting the doc build during initialization if a relationship defined in `traceability_relationships` is missing from it.
Closes #344
> Check traceability_relationship_to_string for completeness

- mlx/traceable_base_node.py
Improved error reporting. When an external relationship was missing from `traceability_external_relationship_to_url`, Sphinx would crash without pointing out the issue.
```
exception: 'NoneType' object has no attribute 'parent'
```
It becomes:
```
exception: Failed to find relationship 'ext_robotframeworklog' in configuration variable 'traceability_external_relationship_to_url'
```
> Raise error when traceability_external_relationship_to_url is incomplete

- doc/configuration.rst
- doc/usage.rst
- mlx/traceability.py
- mlx/traceable_collection.py
- tests/test_traceable_collection.py
- tox.ini
Closes #354
The option `:sort:` of the `item-attributes-matrix` sorts items on attribute values alphabetically. This is good and desired as the default behavior.
A use case for [natural sorting](https://en.wikipedia.org/wiki/Natural_sort_order) on attribute values came up. For example, sorting on values of the attribute `effort` like `11d` and `5d`. 
This PR adds a new configuration value ``traceability_attributes_natsort = {"effort"}``. Any item-attributes-matrix that contains the `effort` attribute will sort on attribute values naturally.
This default value can be overridden in conf.py like all other configuration values.
> Support natural sorting on attributes

- mlx/directives/item_directive.py
- mlx/traceability.py
- tests/directives/test_item_directive.py
When configuration variable `traceability_relationship_to_string` is incomplete, the doc build is exited with `exception: Relationships {'<<relationship_name>>'} are missing from configuration variable 'traceability_relationship_to_string'`.
If this is check for completeness were to be removed, a warning would be reported when this relationship is used: `Traceability: relation <<relationship_name>> cannot be translated to string`. However, this warning is bugged and would crash the doc build with the following error:
```
Traceback (most recent call last):
File "/opt/venv/lib/python3.11/site-packages/sphinx/events.py", line 96, in emit
results.append(listener.handler(self.app, *args))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/venv/lib/python3.11/site-packages/mlx/traceability.py", line …
```
> Clarify error about incomplete traceability_relationship_to_string

- mlx/traceability_exception.py
- mlx/traceable_base_class.py
- mlx/traceable_base_directive.py
- tests/test_traceable_base_class.py
- tests/test_traceable_collection.py
- tests/test_traceable_item.py
The deprecation warnings were added in PR #295 and released on Aug 1, 2022 in v9.0.0.
> Deprecate non-pythonic code

- mlx/traceability/assets/traceability.js
With the configuration of `traceability_collapse_links = True`, our `traceability.js` hides all attributes and relationships when the HTML document is ready. This can cause the viewport to jump, losing focus of the selected traceable item.
This PR should fix this issue. I tested it with Firefox and Chrome.
Closes #363
> Display selected items at the top of the browser viewport

- README.md
- doc/configuration.rst
- mlx/traceability/assets/traceability.js
Make [`traceability_collapse_links = True`](https://melexis.github.io/sphinx-traceability-extension/configuration.html#ability-to-collapse-the-list-of-relationships-and-attributes-per-documentation-object) more user-friendly.
- No longer collapse the traceability information for the selected item
- Show traceability info when clicking item ID (mimicking downward facing arrow)
Closes #362
> Always show the traceability information of selected item

- .github/workflows/python-package.yml
- doc/requirements.rst
- doc/unit_test.rst
- doc/usage.rst
- mlx/traceability/directives/item_matrix_directive.py
- mlx/traceability/directives/item_pie_chart_directive.py
- mlx/traceability/traceable_base_node.py
- tox.ini
> Generate matrix with item-piechart directive

- mlx/traceability/traceable_collection.py
FYI: Items remain "placeholder" when they are not defined with the `item`-directive (or derived directive) and only reference by another item, for example.
> The JSON export should not export a placeholder item as an empty entry

- .github/workflows/python-package.yml
The deployment of v11.3.0 failed because version number 0.0.0 was used. The changes in this MR were missing from #380 .
FYI @gcrabbe
> Fix: Use GIT tag as package version during deployment in CI

- doc/_static/css/extra.css
- doc/usage.rst
- mlx/traceability/assets/traceability.js
- mlx/traceability/directives/item_matrix_directive.py
- mlx/traceability/traceable_base_class.py
- mlx/traceability/traceable_base_node.py
- tests/test_traceable_base_class.py
In HTML, when you right-click a row, the content of all internal items in the row are fetched and displayed.
Successive right-clicks toggle the visibility of the items' content.
The item content is now displayed in a `<div>` element instead of a `<blockquote>` to get rid of the unwanted indentation reported in #377.
FYI @gcrabbe
> item-matrix: Show item content

- doc/integration_test_report.rst
- doc/requirements.rst
- doc/usage.rst
- mlx/traceability/directives/item_matrix_directive.py
- mlx/traceability/traceable_item.py
- tools/doc-warnings.json
> item-matrix: Support recursion via intermediates

- mlx/traceability/directives/item_attribute_directive.py
- mlx/traceability/traceable_base_node.py
- tests/directives/test_item_directive.py
From [Wikipedia](https://en.wikipedia.org/wiki/Colon_(punctuation)#Spacing_and_parentheses):
> In modern [English-language](https://en.wikipedia.org/wiki/English-language) printing, no space is placed before a colon and a single space is placed after it.
> Remove space before colons

- doc/usage.rst
- mlx/traceability/directives/item_directive.py
- tests/directives/test_item_directive.py
- tests/test_html.py
Add option to item-directive to hide specific relation-types in the rendered item definition.
> Add option to item-directive to hide specific relation-types

- doc/conf.py
- doc/configuration.rst
- mlx/traceability/traceability.py
- mlx/traceability/traceable_base_node.py
Register a callback for automatically copying local Javascript resources to the output `_static` directory in order to simplify the configuration.
Inspired by the Sphinx [tutorial](https://www.sphinx-doc.org/en/master/development/html_themes/index.html#add-your-own-static-files-to-the-build-assets).
Generate `hyperlink_colors.css` directly in the output `_static` directory instead of `mlx/traceability/assets` first. Adding files to the package was a bad idea as `pip uninstall mlx.traceability` doesn't clean it up and it can cause permission errors.
> Automatically generate HTML assets in the output directory to simplify the configuration
